### ISSUE TITLE
Default cache version enhancement

### ISSUE THREAD

**Issue by eben-roux** [stealjs/cache-bust#4]
When obtaining the cache version:

`var cacheVersion = loader.cacheVersion || Math.random();`

That `Math.random()` will not be guaranteed to be unique.  However, `new Date().getTime()` would do the trick.

Not a big deal though as typically one should specify the version.

Come to think of it... the cache busting should be applied when not in production as well.  In a previous project we added the date to the urls for development builds to _always_ force a reload.  Would this perhaps be an option?  So use the above suggestion when either no cache version is set _or_ when not in production.

**Comment by matthewp** [comment]
Sounds good to me!  PR welcome if you want to make this enhancement.

**Comment by eben-roux** [comment]
Right... will do a PR :)

**Comment by matthewp** [comment]
Closed by #6
